FROM docker.io/denoland/deno:2.3.2

RUN apt-get update && apt-get install -y build-essential ffmpeg jq && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY web/fonts /app/web/fonts

COPY deno.json /app/deno.json
COPY ai/deno.json /app/ai/deno.json
COPY federation/deno.json /app/federation/deno.json
COPY graphql/deno.json /app/graphql/deno.json
COPY models/deno.json /app/models/deno.json
COPY web/deno.json /app/web/deno.json
COPY deno.lock /app/deno.lock

RUN ["deno", "install"]

COPY . /app
RUN cp .env.sample .env && \
  sed -i '/^INSTANCE_ACTOR_KEY=/d' .env && \
  echo >> .env && \
  echo "INSTANCE_ACTOR_KEY='$(deno task keygen)'" >> .env && \
  deno task build && \
  rm .env

EXPOSE 8000
CMD ["deno", "task", "start"]
